# Generated by Django 5.2.5 on 2025-09-05 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_date", models.DateField(verbose_name="date created")),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField()),
                ("sort_index", models.IntegerField(default=0)),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reflections.configuration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reflections.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reflection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_date", models.DateField(verbose_name="reflection date")),
                (
                    "questions",
                    models.ManyToManyField(
                        through="reflections.Answer",
                        through_fields=("reflection", "question"),
                        to="reflections.question",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="answer",
            name="reflection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reflections.reflection"
            ),
        ),
    ]
